FROM gradle:jdk16 AS build
COPY --chown=maven:maven . /home/maven/src
WORKDIR /home/maven/src
RUN gradle --no-daemon bootJar

FROM openjdk:16
RUN mkdir /app
COPY --from=build /home/maven/src/build/libs/*.jar /app/spring-boot-application.jar
EXPOSE 8080
CMD ["java","-jar", "-Xmx4g", "/app/spring-boot-application.jar"]
